# .github/workflows/build-windows.yml
# 
# This workflow builds ASTRA.exe for Windows from any OS.
# 
# Setup:
#   1. Create folder: .github/workflows/ in your repo
#   2. Put this file there
#   3. Push to GitHub
#   4. Go to Actions tab → Run workflow
#   5. Download the artifact (ASTRA-Windows.zip)

name: Build Windows EXE

on:
  workflow_dispatch:  # Manual trigger from GitHub Actions tab
  push:
    tags:
      - 'v*'  # Also triggers on version tags like v2.1.2

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
        shell: cmd

      - name: Build Windows EXE
        run: |
          pyinstaller ^
            --noconfirm ^
            --clean ^
            --onedir ^
            --windowed ^
            --name "ASTRA" ^
            --icon "icon.ico" ^
            "main.py" ^
            --exclude-module nltk ^
            --add-data "frontend;frontend" ^
            --add-data ".env;." ^
            --add-data "backend\.env;backend" ^
            --add-data "data;data" ^
            --add-data "backend\templates;backend\templates" ^
            --add-data "backend\api\base_coverletter.tex;backend\api" ^
            --add-data "backend\api\base_resume.tex;backend\api" ^
            --collect-submodules backend ^
            --hidden-import backend.api.optimize ^
            --hidden-import backend.api.coverletter ^
            --hidden-import backend.api.talk ^
            --hidden-import backend.api.superhuman ^
            --hidden-import backend.api.humanize ^
            --hidden-import backend.api.mastermind ^
            --hidden-import backend.api.dashboard ^
            --hidden-import backend.api.models_router ^
            --hidden-import backend.api.context_store ^
            --hidden-import backend.api.utils_router ^
            --hidden-import backend.api.debug ^
            --hidden-import backend.core.config ^
            --hidden-import backend.core.compiler ^
            --hidden-import backend.core.utils ^
            --hidden-import backend.core.security ^
            --hidden-import backend.core.mastermind_memory ^
            --hidden-import uvicorn ^
            --hidden-import uvicorn.logging ^
            --hidden-import uvicorn.loops ^
            --hidden-import uvicorn.loops.auto ^
            --hidden-import uvicorn.protocols ^
            --hidden-import uvicorn.protocols.http ^
            --hidden-import uvicorn.protocols.http.auto ^
            --hidden-import uvicorn.protocols.websockets ^
            --hidden-import uvicorn.protocols.websockets.auto ^
            --hidden-import uvicorn.lifespan ^
            --hidden-import uvicorn.lifespan.on ^
            --hidden-import fastapi ^
            --hidden-import starlette ^
            --hidden-import dotenv ^
            --hidden-import pydantic ^
            --hidden-import httptools ^
            --hidden-import websockets ^
            --hidden-import anyio
        shell: cmd

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: ASTRA-Windows
          path: dist/ASTRA/
          retention-days: 30
